### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by mukesh1811** [rorytboyle/hierarchical_regression#2]
Hi! Thanks a lot for your initiative.. It would be great if you can add an example notebook explaining how to use this.

**Comment by rorytboyle** [comment]
Hi,

I wrote this code for an analysis I completed for a research project on cognitive reserve. You can read this journal article which describes the use of this code in that project: https://doi.org/10.1186%2Fs13195-021-00870-z. 

The purpose of this repository is to make this code available to other researchers who want to examine and use this code for similar purposes (investigate the validity of proxy measures of cognitive reserve). I don't have time to write up an example notebook further explaining how to use this. The code itself is well-documented though so it should be possible to read through the code and figure out how to use it.
